### ISSUE TITLE
Increase memory limit for the workshop.

### ISSUE THREAD

**Issue by GrahamDumpleton** [everythingeverywhere/lab-spring-gateway#1]
In:

* https://github.com/everythingeverywhere/lab-spring-gateway/blob/master/workshop/content/exercises/03-test-route.md

you state:

> Note: If you don't have any errors in the output and you are having trouble keep executing spring-boot:run. This is due to lab constraints

This is because Java takes lots of memory. As a result you need to increase the amount of memory given to the workshop.

This is done in the ``resources/workshop.yaml`` file as explained in:

* https://docs.edukates.io/en/latest/runtime-environment/workshop-definition.html#overriding-the-memory-available

Other Java/Spring workshops use 2Gi. For example:

* https://github.com/eduk8s-labs/lab-spring-boot-k8s-skaffold/blob/master/resources/workshop.yaml#L17

**Comment by everythingeverywhere** [comment]
What sage advice it solved this issue!
