### ISSUE TITLE
Automate actions for editing files to streamline steps.

### ISSUE THREAD

**Issue by GrahamDumpleton** [everythingeverywhere/lab-spring-gateway#2]
Describing manual steps for people to edit files can be confusing and prone to errors. It is better to make use of clickable actions to create and edit files. For details of markup to do this see:

* https://docs.edukates.io/en/latest/workshop-content/page-formatting.html#clickable-actions-for-the-editor

It is recommended early on in the workshop to have the user open the editor to get it started before first clickable action against it, as it can be slow otherwise.

For example:

* https://raw.githubusercontent.com/eduk8s-labs/lab-spring-boot-k8s-skaffold/master/workshop/content/setup-environment.md

See the Spring Skaffold and Probes workshops for examples of how it works in practice.

**Comment by everythingeverywhere** [comment]
Thanks Graham for all your help!!! This was brilliant this makes the workshop so easy you can click your way through to the last step and less error prone.

**Comment by everythingeverywhere** [comment]
This took me longer than I would like to admit lol but I was a bit distracted yesterday :)

**Comment by everythingeverywhere** [comment]
I hope the lab is in better shape. I also made you a collaborator in this and in the [microservices lab](https://github.com/everythingeverywhere/lab-microservice).
