### ISSUE TITLE
Use jdk11-environment:* for content.image.

### ISSUE THREAD

**Issue by GrahamDumpleton** [everythingeverywhere/lab-spring-gateway#3]
If your workshop requires JDK 11 and you don't need a custom workshop image, use:

```
  content:
    image: jdk11-environment:*
    files: github.com/everythingeverywhere/lab-spring-gateway
```

The value `jdk11-environment:*` will be mapped by the operator to whatever JDK 11 image the operator is configured to use for that version of the operator.

Details in:

* https://docs.edukates.io/en/latest/runtime-environment/workshop-definition.html#container-image-for-the-workshop

**Comment by everythingeverywhere** [comment]
thanks Graham updated this!
